import React,{useMemo,useRef,useState}from'react';
import { Archive, ArrowRight, BookOpen, Briefcase, Download, Dumbbell, FileUp, Gauge, Landmark, Newspaper, Save, ShieldCheck, Sparkles, Target, Trash2, Trophy, Users, Wrench } from 'lucide-react';
import { careerNews, difficultyProfile, dynamicRivalries, managerCareerSummary, managerProfile, promoteAcademyProspect, resolvePressConference, squadHierarchyFor } from './career-dynamics.js';
import { financeHealth } from './economy-engine.js';
import { worldClub, worldCompetitionList } from './competition-engine.js';
import { deleteManualSaveSlot, listManualSaveSlots, parseCareerSave, saveFileName, serializeCareerSave, writeManualSaveSlot } from './save-format.js';
import { acceptJobOffer, declineJobOffer, expiringContracts, makePlayerPromise, renewPlayerContract, upgradeFacility } from './career-life-engine.js';
import { TACTICAL_PRESETS, TRAINING_FOCUS, sanitizeTacticalState, setTacticalPreset, setTrainingFocus, updateTacticalState } from './tactical-engine.js';
import WorldCrest from './WorldCrest.jsx';
import './career-center.css';

const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
function localHash(value){let h=2166136261;for(const ch of String(value)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
function spectatorTimeline(result){
  const events=[];
  for(let i=0;i<Number(result?.homeGoals||0);i++)events.push({side:'home',minute:7+(localHash(result.id+'|h|'+i)%82)});
  for(let i=0;i<Number(result?.awayGoals||0);i++)events.push({side:'away',minute:7+(localHash(result.id+'|a|'+i)%82)});
  return events.sort((a,b)=>a.minute-b.minute);
}

function SavePanel({career,club,onImportCareer}){
  const input=useRef(null),[notice,setNotice]=useState(''),[slots,setSlots]=useState(()=>{try{return listManualSaveSlots();}catch{return[];}});
  const refresh=()=>{try{setSlots(listManualSaveSlots());}catch{setSlots([]);}};
  function download(){
    try{
      const blob=new Blob([serializeCareerSave(career,club)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');
      a.href=url;a.download=saveFileName(career,club);document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Backup criado. Guarde o arquivo .ldf onde preferir.');
    }catch{setNotice('Não foi possível criar o arquivo neste navegador.');}
  }
  async function load(file){
    if(!file)return;
    try{const payload=parseCareerSave(await file.text());await onImportCareer?.(payload);setNotice('Save carregado com sucesso.');}
    catch(error){setNotice(error?.message||'Não foi possível carregar este save.');}
    if(input.current)input.current.value='';
  }
  function saveSlot(slot){
    try{writeManualSaveSlot(slot,career,club);refresh();setNotice('Slot '+slot+' atualizado. O autosave continua funcionando normalmente.');}
    catch(error){setNotice(error?.message||'Não foi possível salvar neste slot.');}
  }
  async function loadSlot(item){
    if(item.empty||!item.payload)return;
    try{await onImportCareer?.(item.payload);setNotice('Slot '+item.slot+' carregado.');}
    catch(error){setNotice(error?.message||'Não foi possível carregar este slot.');}
  }
  function removeSlot(slot){try{deleteManualSaveSlot(slot);refresh();setNotice('Slot '+slot+' apagado.');}catch{setNotice('Não foi possível apagar este slot.');}}
  return <section className="center-save">
    <div className="center-section-head"><div><Archive size={18}/><span><small>SAVES & BACKUP</small><strong>Seu save pertence a você</strong></span></div></div>
    <p>O autosave continua no navegador. Use os slots para checkpoints rápidos e o arquivo <b>.ldf</b> como backup portátil para outro navegador ou aparelho.</p>
    <div className="manual-save-slots">{slots.map(item=><article key={item.slot} className={item.empty?'empty':''}><div><small>SLOT {item.slot}</small><strong>{item.empty?'Vazio':item.club?.name||'Carreira salva'}</strong><span>{item.empty?'Disponível para um checkpoint':('Temporada '+item.season+(item.managerName?' · '+item.managerName:''))}</span></div><div className="manual-slot-actions"><button onClick={()=>saveSlot(item.slot)}><Save size={14}/>{item.empty?'Salvar':'Sobrescrever'}</button>{!item.empty&&<button className="slot-load" onClick={()=>loadSlot(item)}><FileUp size={14}/>Carregar</button>}{!item.empty&&<button className="slot-delete" aria-label={'Apagar slot '+item.slot} onClick={()=>removeSlot(item.slot)}><Trash2 size={14}/></button>}</div></article>)}</div>
    <div className="save-actions"><button onClick={download}><Download size={16}/> Baixar save .ldf</button><button className="secondary-save" onClick={()=>input.current?.click()}><FileUp size={16}/> Importar .ldf</button><input ref={input} type="file" accept=".ldf,application/json" hidden onChange={e=>load(e.target.files?.[0])}/></div>
    {notice&&<span className="save-notice">{notice}</span>}
  </section>;
}

export default function CareerCenter({career,club,clubs,Crest,onCareerChange,onImportCareer}){
  const [tab,setTab]=useState('news'),[actionNotice,setActionNotice]=useState(''),[spectatorMatch,setSpectatorMatch]=useState(null),crestFor=item=>item?.external?<WorldCrest club={item} size="mini"/>:<Crest club={item}/>;
  const news=useMemo(()=>careerNews(career),[career]),summary=useMemo(()=>managerCareerSummary(career),[career]),rivalries=useMemo(()=>dynamicRivalries(career,clubs).slice(0,8),[career,clubs]),competitions=useMemo(()=>worldCompetitionList(career,clubs),[career,clubs]),contracts=useMemo(()=>expiringContracts(career,club,1).slice(0,8),[career,club]),universeMatches=useMemo(()=>(career.world?.history||[]).filter(item=>String(item.homeId)!==String(career.userClubId)&&String(item.awayId)!==String(career.userClubId)).slice(0,8),[career.world?.history,career.userClubId]),finance=financeHealth(career),difficulty=difficultyProfile(career,club),profile=managerProfile(career.managerProfile),room=career.dressingRoom||{},president=career.presidentProfile||{},dna=career.clubDNA||{},academy=career.youthAcademy||{prospects:[]},tactic=sanitizeTacticalState(career.tacticalState),facilities=career.facilities||{},activePromises=(career.playerPromises||[]).filter(item=>item.status==='active'),jobOffers=(career.jobOffers||[]).filter(item=>item.status==='open'),worldManagers=Object.values(career.worldManagers||{}).slice(0,10);
  const hierarchyLeaders=Object.values(squadHierarchyFor(club)).filter(item=>item.tier==='leader').sort((a,b)=>b.influence-a.influence).slice(0,4);
  const tabs=[['news','Notícias',Newspaper],['club','Clube',ShieldCheck],['planning','Planejamento',Dumbbell],['academy','Base',Users],['universe','Universo',Landmark],['legacy','Carreira',Trophy],['save','Save',Archive]];
  function promote(id){onCareerChange(promoteAcademyProspect(career,club,id));}
  function press(choice){onCareerChange(resolvePressConference(career,choice));}
  function chooseTactic(id){onCareerChange(setTacticalPreset(career,id));}
  function changeTacticField(key,value){onCareerChange(updateTacticalState(career,{[key]:Number(value)}));}
  function chooseTraining(id){onCareerChange(setTrainingFocus(career,id));}
  function promiseMinutes(playerId){onCareerChange(makePlayerPromise(career,club,playerId,'minutes'));}
  function renew(playerId){const result=renewPlayerContract(career,club,playerId,3);if(result.error){setActionNotice(result.error);return;}setActionNotice('Contrato renovado por três temporadas.');onCareerChange(result.career);}
  function improve(type){const result=upgradeFacility(career,type);if(result.error){setActionNotice(result.error);return;}setActionNotice('Estrutura atualizada.');onCareerChange(result.career);}
  function acceptOffer(id){const result=acceptJobOffer(career,clubs,id);if(result.error){setActionNotice(result.error);return;}setActionNotice('Novo projeto assumido.');onCareerChange(result.career);}
  function rejectOffer(id){setActionNotice('Proposta recusada.');onCareerChange(declineJobOffer(career,id));}
  return <div className="career-center">
    <header className="center-heading"><div><span className="eyebrow">BASTIDORES DA CARREIRA</span><h2>Bastidores</h2><p>O que acontece no campo, no mercado e no vestiário deixa consequências no seu universo.</p></div><span className="center-reputation">Reputação <strong>{summary.reputation}</strong></span></header>
    <nav className="center-tabs">{tabs.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={15}/>{label}</button>)}</nav>

    {career.pressConference&&<section className="press-card"><div><span className="eyebrow">IMPRENSA</span><h3>Uma resposta pode mudar o ambiente.</h3><p>{career.pressConference.reason==='clássico'?'A rivalidade elevou o tom antes do próximo capítulo.':career.pressConference.reason==='decisão'?'A decisão aumentou a pressão externa.':'A sequência recente colocou o trabalho em debate.'}</p></div><div className="press-choices">{career.pressConference.choices.map(choice=><button key={choice.id} onClick={()=>press(choice.id)}><strong>{choice.label}</strong><span>{choice.copy}</span></button>)}</div></section>}

    {tab==='news'&&<section className="news-feed"><div className="center-section-head"><div><Newspaper size={18}/><span><small>REDAÇÃO DO SAVE</small><strong>Notícias do seu universo</strong></span></div><em>{news.length} registros</em></div>{news.length?<div className="news-list">{news.slice(0,30).map(item=><article key={item.id} className={'news-item importance-'+(item.importance||1)}><span>{item.type==='title'?<Trophy size={17}/>:item.type==='injury'?<ShieldCheck size={17}/>:<BookOpen size={17}/>}</span><div><small>{String(item.type||'clube').toUpperCase()} · {item.timestamp||('Rodada '+item.round)}</small><h3>{item.title}</h3><p>{item.text}</p></div></article>)}</div>:<p className="center-empty">A redação começa a acompanhar a carreira assim que a bola rolar.</p>}</section>}

    {tab==='club'&&<div className="center-club-grid">
      <section className="manager-identity"><div className="center-section-head"><div><ShieldCheck size={18}/><span><small>SEU PERFIL</small><strong>{profile.name}</strong></span></div></div><p>{profile.description}</p><dl><div><dt>Reputação</dt><dd>{summary.reputation}/100</dd></div><div><dt>Dificuldade orgânica</dt><dd>{difficulty.label}</dd></div><div><dt>Torcida</dt><dd>{Math.round(career.managerConfidence?.fans||0)}%</dd></div><div><dt>Diretoria</dt><dd>{Math.round(career.managerConfidence?.board||0)}%</dd></div></dl></section>
      <section className="manager-identity"><div className="center-section-head"><div><Users size={18}/><span><small>VESTIÁRIO</small><strong>Ambiente do grupo</strong></span></div></div><div className="room-bars"><span>Ânimo <b>{Math.round(room.morale||0)}%</b><i><em style={{width:(room.morale||0)+'%'}}/></i></span><span>União <b>{Math.round(room.unity||0)}%</b><i><em style={{width:(room.unity||0)+'%'}}/></i></span></div>{hierarchyLeaders.length>0&&<div className="room-hierarchy"><small>LIDERANÇAS DO ELENCO</small><div>{hierarchyLeaders.map(item=><span key={item.key}><b>{item.name}</b><em>{item.overall} OVR</em></span>)}</div></div>}{Object.values(room.playerMood||{}).filter(x=>x.unhappy).slice(0,3).map(item=><div className="room-alert promise-alert" key={item.name}><span>{item.name} está incomodado com a sequência no banco.</span>{!activePromises.some(p=>p.key===item.key)&&<button onClick={()=>promiseMinutes(item.key?.split(':').pop())}>Prometer minutos</button>}</div>)}</section>
      <section className="manager-identity"><div className="center-section-head"><div><Landmark size={18}/><span><small>DIRETORIA</small><strong>{president.name||'Diretoria do clube'}</strong></span></div></div><p>{president.description}</p><div className="dna-tags">{(dna.labels||[]).map(item=><span key={item}>{item}</span>)}</div></section>
      <section className="manager-identity finance-health-card"><div className="center-section-head"><div><Archive size={18}/><span><small>ESTRUTURA FINANCEIRA</small><strong>{finance.label}</strong></span></div></div><dl><div><dt>Orçamento de mercado</dt><dd>{money.format(finance.budget)}</dd></div><div><dt>Espaço salarial</dt><dd>{money.format(finance.wageRoom)}/mês</dd></div><div><dt>Reinvestimento</dt><dd>{Math.round(finance.reinvestmentRate*100)}%</dd></div><div><dt>Caixa</dt><dd>{money.format(finance.cash)}</dd></div></dl></section>
    </div>}

    {tab==='planning'&&<div className="planning-stack">
      <section className="planning-panel"><div className="center-section-head"><div><Gauge size={18}/><span><small>IDENTIDADE TÁTICA</small><strong>{TACTICAL_PRESETS.find(item=>item.id===tactic.preset)?.name||'Equilibrado'}</strong></span></div></div><p>Escolha uma base e refine os detalhes. A engine transforma essas escolhas em xG, posse, fadiga, risco e transições.</p><div className="tactic-preset-grid">{TACTICAL_PRESETS.map(item=><button key={item.id} className={tactic.preset===item.id?'active':''} onClick={()=>chooseTactic(item.id)}><strong>{item.name}</strong><span>{item.description}</span></button>)}</div><div className="tactic-sliders">{[['pressing','Pressão'],['defensiveLine','Linha defensiva'],['tempo','Ritmo'],['risk','Risco']].map(([key,label])=><label key={key}><span>{label}<b>{Math.round(tactic[key])}</b></span><input type="range" min="0" max="100" value={tactic[key]} onChange={e=>changeTacticField(key,e.target.value)}/></label>)}</div><div className="setpiece-row"><span><small>ESCANTEIOS</small><strong>Bola parada</strong></span>{[['mixed','Misto'],['near-post','1º poste'],['far-post','2º poste'],['short','Curto']].map(([id,label])=><button key={id} className={tactic.setPieces?.corners===id?'active':''} onClick={()=>onCareerChange(updateTacticalState(career,{setPieces:{corners:id}}))}>{label}</button>)}</div></section>
      <section className="planning-panel"><div className="center-section-head"><div><Dumbbell size={18}/><span><small>SEMANA DE TREINO</small><strong>{TRAINING_FOCUS.find(item=>item.id===(career.trainingState?.focus||'balanced'))?.name}</strong></span></div></div><div className="training-grid">{TRAINING_FOCUS.map(item=><button key={item.id} className={(career.trainingState?.focus||'balanced')===item.id?'active':''} onClick={()=>chooseTraining(item.id)}><strong>{item.name}</strong><span>{item.description}</span></button>)}</div></section>
      <section className="planning-panel"><div className="center-section-head"><div><Wrench size={18}/><span><small>ESTRUTURA</small><strong>Investimentos de longo prazo</strong></span></div></div><div className="facility-grid">{[['training','CT'],['medical','Departamento médico'],['academy','Base'],['scouting','Scouting']].map(([id,label])=><article key={id}><span><small>{label.toUpperCase()}</small><strong>Nível {facilities[id]||1}/5</strong></span><button disabled={(facilities[id]||1)>=5} onClick={()=>improve(id)}>{(facilities[id]||1)>=5?'Máximo':'Melhorar'}</button></article>)}</div></section>
      <section className="planning-panel"><div className="center-section-head"><div><Target size={18}/><span><small>PROJETO</small><strong>Metas de médio prazo</strong></span></div></div><div className="objective-list">{(career.projectObjectives||[]).map(item=><article key={item.id} className={item.status}><span>{item.label}</span><b>{item.status==='active'?'até '+item.targetSeason:item.status==='completed'?'cumprida':'não cumprida'}</b></article>)}</div></section>
      <section className="planning-panel"><div className="center-section-head"><div><Users size={18}/><span><small>CONTRATOS</small><strong>Vínculos próximos do fim</strong></span></div></div>{contracts.length?<div className="contract-list">{contracts.map(({player,contract})=><article key={contract.key}><div><strong>{player.name}</strong><span>até {contract.expirySeason} · {money.format(contract.salaryMonthly)}/mês</span></div><button onClick={()=>renew(player.id)}>Renovar 3 anos</button></article>)}</div>:<p className="center-empty">Nenhum vínculo importante vence nas próximas duas temporadas.</p>}</section>
      <section className="planning-panel"><div className="center-section-head"><div><Briefcase size={18}/><span><small>MERCADO DE TÉCNICOS</small><strong>Convites para novos projetos</strong></span></div></div>{jobOffers.length?<div className="job-offer-list">{jobOffers.map(item=><article key={item.id}><div><strong>{item.clubName}</strong><span>{item.project} · proposta válida por mais {Math.max(0,item.expiresAtMatch-(career.careerRecord?.matches||0))} jogos</span></div><div><button onClick={()=>acceptOffer(item.clubId)}>Aceitar</button><button className="secondary-job" onClick={()=>rejectOffer(item.id)}>Recusar</button></div></article>)}</div>:<p className="center-empty">Seu mercado depende de reputação, resultados e do tamanho do projeto atual. Novas consultas aparecem organicamente.</p>}</section>
      {actionNotice&&<p className="planning-notice">{actionNotice}</p>}
    </div>}

    {tab==='academy'&&<section className="academy-panel"><div className="center-section-head"><div><Users size={18}/><span><small>CATEGORIAS DE BASE</small><strong>Geração {academy.lastIntakeSeason||career.season}</strong></span></div><em>Nível {academy.level||1}</em></div><p className="academy-intro">Cada geração é diferente. Alguns jovens têm teto alto, outros podem nunca se firmar. A avaliação não mostra o potencial exato.</p><div className="academy-grid">{(academy.prospects||[]).map(p=>{const projection=p.potential>=86?'Potencial especial':p.potential>=78?'Boa projeção':p.potential>=70?'Pode evoluir':'Em observação';return <article key={p.id} className={p.status==='promoted'?'promoted':''}><span className="academy-monogram">{p.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div><h3>{p.name}</h3><p>{p.age} anos · {p.position} · OVR atual {p.overall}</p><small>{projection}</small></div>{p.status==='academy'?<button onClick={()=>promote(p.id)}>Subir ao profissional <ArrowRight size={14}/></button>:<b>Promovido</b>}</article>})}</div></section>}

    {tab==='universe'&&<div className="universe-grid"><section><div className="center-section-head"><div><Landmark size={18}/><span><small>COMPETIÇÕES</small><strong>Universo do save</strong></span></div></div><div className="universe-competitions">{competitions.map(comp=>{const champion=comp.championId?worldClub(career,clubs,comp.championId):null;return <article key={comp.key}><div><strong>{comp.name}</strong><small>{comp.stage||'Em andamento'} · {comp.edition}</small></div>{champion?<span>{crestFor(champion)}{champion.name}</span>:<em>em disputa</em>}</article>})}</div></section><section><div className="center-section-head"><div><Sparkles size={18}/><span><small>RIVALIDADES</small><strong>Histórias que surgiram no save</strong></span></div></div>{rivalries.length?<div className="rivalry-list">{rivalries.map(item=><article key={item.clubId}><strong>{item.name}</strong><span>{item.label}</span><i><b style={{width:item.score+'%'}}/></i><small>{item.meetings} encontros · {item.userWins} vitórias suas · {item.opponentWins} do rival</small></article>)}</div>:<p className="center-empty">Rivalidades emergentes aparecerão conforme confrontos se repetirem e ganharem importância.</p>}</section><section><div className="center-section-head"><div><Briefcase size={18}/><span><small>MERCADO DE TÉCNICOS</small><strong>Os bancos também mudam</strong></span></div></div><div className="universe-managers">{worldManagers.map(item=>{const managed=clubs.find(c=>String(c.id)===String(item.clubId));return <article key={item.clubId}>{managed&&crestFor(managed)}<span><strong>{item.name}</strong><small>{managed?.name||item.clubId} · desde {item.sinceSeason}</small></span></article>})}</div></section><section><div className="center-section-head"><div><Target size={18}/><span><small>MODO ESPECTADOR</small><strong>Jogos do restante do universo</strong></span></div></div>{universeMatches.length?<div className="spectator-list">{universeMatches.map(match=>{const home=worldClub(career,clubs,match.homeId),away=worldClub(career,clubs,match.awayId);return <button key={match.id} onClick={()=>setSpectatorMatch(match)}><span>{crestFor(home)}{home?.abbreviation||home?.name}</span><strong>{match.homeGoals} × {match.awayGoals}</strong><span>{away?.abbreviation||away?.name}{crestFor(away)}</span><small>{match.competitionName} · {match.stage}</small></button>})}</div>:<p className="center-empty">Os jogos de outros clubes aparecerão aqui conforme o calendário avançar.</p>}</section></div>}

    {tab==='legacy'&&<div className="legacy-center"><section className="manager-career-card"><Crest club={club}/><span><small>CARREIRA DE {career.managerName||'TÉCNICO'}</small><strong>{summary.reputation} de reputação</strong></span><dl><div><dt>Jogos</dt><dd>{summary.matches}</dd></div><div><dt>Vitórias</dt><dd>{summary.wins}</dd></div><div><dt>Títulos</dt><dd>{summary.titles}</dd></div><div><dt>Clubes</dt><dd>{summary.clubsManaged||1}</dd></div></dl></section><section><div className="center-section-head"><div><Trophy size={18}/><span><small>HALL DA FAMA DO SAVE</small><strong>Quem marcou a sua história</strong></span></div></div>{career.hallOfFame?.players?.length?<div className="hof-list">{career.hallOfFame.players.map(item=><article key={item.name+'-'+item.season}><strong>{item.name}</strong><span>{item.reason} · {item.season}</span><b>{item.rating?.toFixed?.(2)||item.rating}</b></article>)}</div>:<p className="center-empty">O Hall da Fama começa a ganhar nomes após temporadas completas.</p>}{career.hallOfFame?.moments?.slice(0,8).map(item=><p className="historic-moment" key={item.id}><b>{item.title}</b> · {item.text}</p>)}</section><section className="career-timeline"><div className="center-section-head"><div><BookOpen size={18}/><span><small>LINHA DO TEMPO</small><strong>A carreira que este save construiu</strong></span></div></div><div className="timeline-list">{[...(career.managerClubHistory||[]).map(item=>({id:'club-'+item.clubId+'-'+item.fromSeason,season:item.fromSeason,title:'Assumiu '+item.clubName,text:item.toSeason?'Projeto encerrado em '+item.toSeason:'Projeto atual'})),...(career.careerMemory?.milestones||[])].sort((a,b)=>Number(b.season||0)-Number(a.season||0)).slice(0,30).map(item=><article key={item.id}><b>{item.season}</b><span><strong>{item.title}</strong><small>{item.text||''}</small></span></article>)}</div></section></div>}

    {spectatorMatch&&<div className="spectator-overlay" onClick={e=>{if(e.target===e.currentTarget)setSpectatorMatch(null)}}><section className="spectator-card"><button className="spectator-close" onClick={()=>setSpectatorMatch(null)}>×</button>{(()=>{const home=worldClub(career,clubs,spectatorMatch.homeId),away=worldClub(career,clubs,spectatorMatch.awayId),timeline=spectatorTimeline(spectatorMatch);return <><span className="eyebrow">MODO ESPECTADOR · {spectatorMatch.competitionName}</span><div className="spectator-score"><span>{crestFor(home)}<strong>{home?.name}</strong></span><b>{spectatorMatch.homeGoals} × {spectatorMatch.awayGoals}</b><span><strong>{away?.name}</strong>{crestFor(away)}</span></div><p>{spectatorMatch.stage} · {spectatorMatch.date}</p><div className="spectator-events">{timeline.length?timeline.map((event,index)=><span key={index}><b>{event.minute}'</b> ⚽ {event.side==='home'?(home?.name||'Mandante'):(away?.name||'Visitante')}</span>):<span>90' · partida sem gols</span>}</div></>})()}</section></div>}
    {tab==='save'&&<SavePanel career={career} club={club} onImportCareer={onImportCareer}/>}
  </div>;
}
