import React, {useState} from 'react';
import { ArrowRight, Award, BadgeCheck, Check, FlaskConical, Handshake, LockKeyhole, Plus, Shield, Trophy, Wallet } from 'lucide-react';
import { offers, slots, trophies, contractTotals, signContract } from './management-model';
import './management.css';
const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(n);
function Cup({shape,won}) {
  return <svg className={`cup-art ${won?'won':''}`} viewBox="0 0 120 140" fill="none" aria-hidden="true">
    <ellipse cx="60" cy="131" rx="39" ry="5" fill="currentColor" opacity=".12"/>
    {shape==='league'?<><path d="M30 22h60L77 83H43Z" fill="currentColor" opacity=".3"/><path d="M30 22h60L77 83H43Z M36 22l14 61m-3-61 8 61m18-61-8 61m19-61L70 83M60 22v61" stroke="currentColor" strokeWidth="3"/><path d="M43 18h34v8H43zM48 83h24v9H48zM55 92h10v24H55zM39 117h42v10H39z" fill="currentColor"/></>:shape==='cup'?<><path d="M36 26H18v16c0 19 17 29 31 29M84 26h18v16c0 19-17 29-31 29" stroke="currentColor" strokeWidth="5"/><path d="M31 18h58l-6 40c-2 14-12 25-23 25S39 72 37 58Z" fill="currentColor" opacity=".65"/><path d="M60 81v31M41 120h38" stroke="currentColor" strokeWidth="8"/><path d="M37 17h46" stroke="currentColor" strokeWidth="5"/></>:shape==='globe'?<><circle cx="60" cy="34" r="22" fill="currentColor" opacity=".6"/><ellipse cx="60" cy="34" rx="10" ry="22" stroke="currentColor" strokeWidth="2"/><path d="M38 34h44M60 57v43M39 105h42v20H39z" stroke="currentColor" strokeWidth="6"/><path d="M49 62h22l7 40H42z" fill="currentColor" opacity=".35"/></>:<><path d="M60 13 38 83l22 26 22-26Z" fill="currentColor" opacity=".55"/><path d="M60 13v96M38 83h44M47 59h26" stroke="currentColor" strokeWidth="3"/><path d="M55 106h10v11H55zM39 117h42v10H39z" fill="currentColor"/></>}
  </svg>;
}
export default function Management({club,tab,state,update,canManage,onChoose,Modal,storageError}) {
  const [filter,setFilter]=useState('Todos'); const [pending,setPending]=useState(null); const [notice,setNotice]=useState('');
  const totals=contractTotals(state);
  const active=offers.filter(o=>state.contracts.includes(o.id));
  function apply() {
    if(!canManage) {setPending(null);return;}
    const {type,item}=pending;
    update(previous=>type==='sign'?signContract(previous,item.id):type==='end'?{...previous,contracts:previous.contracts.filter(id=>id!==item.id)}:type==='award'?{...previous,awards:[...new Set([...previous.awards,item.id])]}:{...previous,awards:previous.awards.filter(id=>id!==item.id)});
    setNotice(type==='sign'?`Contrato com ${item.name} adicionado à simulação.`:type==='end'?'Contrato encerrado na simulação.':type==='award'?'Conquista de teste adicionada à galeria.':'Conquista de teste removida.');setPending(null);
  }
  return <div className="management-content">
    <div className="management-heading"><div><div className="eyebrow">{tab==='trophies'?'O PESO DA SUA CAMISA':'FORA DAS QUATRO LINHAS'}</div><h2>{tab==='trophies'?'Galeria de troféus':'Patrocínios'}</h2><p>{tab==='trophies'?`As conquistas da sua gestão no ${club.name}.`:'Boas parcerias constroem grandes equipes.'}</p></div><span className="lab-badge"><FlaskConical size={13}/> Laboratório</span></div>
    {storageError&&<p className="management-alert" role="alert">O navegador não permitiu salvar. As alterações ficam disponíveis apenas nesta sessão.</p>}
    {!canManage&&<div className="choose-notice"><Shield size={19}/><p>Escolha o {club.name} para testar a gestão deste clube.</p><button onClick={onChoose}>Escolher clube <ArrowRight size={15}/></button></div>}
    {notice&&<div className="management-notice" role="status"><Check size={15}/>{notice}</div>}
    {tab==='trophies'?<>
      <div className="trophy-overview"><div className="laurel"><Trophy size={32}/></div><div><span className="eyebrow">SUA SALA DE CONQUISTAS</span><h3>{state.awards.length? 'O começo de um legado.':'O próximo troféu pode ser seu.'}</h3><p>{state.awards.length?'Conquistas simuladas para testar a galeria.':'Cada temporada é uma chance de fazer história.'}</p></div><div className="trophy-count"><strong>{String(state.awards.length).padStart(2,'0')}</strong><span>conquistas de teste</span></div></div>
      <div className="gallery-toolbar"><div className="position-tabs" aria-label="Filtrar troféus">{['Todos','Nacional','Continental'].map(f=><button key={f} aria-pressed={filter===f} className={filter===f?'current':''} onClick={()=>setFilter(f)}>{f==='Nacional'?'Nacionais':f==='Continental'?'Continentais':'Todas as taças'}</button>)}</div><span>Temporada de teste · 2026</span></div>
      <div className="trophy-grid">{trophies.filter(t=>filter==='Todos'||filter===t.kind).map(t=>{const won=state.awards.includes(t.id);return <article key={t.id} className={`trophy-card ${won?'earned':''}`}><div className="trophy-card-top"><span>{t.kind}</span>{won?<span className="won-badge"><BadgeCheck size={12}/> TESTE · 2026</span>:<LockKeyhole size={13}/>}</div><Cup shape={t.shape} won={won}/><h3>{t.name}</h3><p>{t.label}</p><span className="trophy-state">{won?'Conquista simulada':t.id==='brasileirao'?'A conquistar':'Competição prevista para etapa futura'}</span><button disabled={!canManage} onClick={()=>setPending({type:won?'removeAward':'award',item:t})}>{won?'Remover teste':'Testar conquista'}{won?<Check size={14}/>:<Plus size={14}/>}</button></article>;})}</div>
      <div className="module-footnote"><FlaskConical size={15}/><p>Esta galeria registra conquistas da sua carreira, não o histórico real do clube. Os botões de teste permitem conferir o visual; partidas e premiações automáticas ainda não estão disponíveis. As ilustrações são estilizadas.</p></div>
    </>:<>
      <div className="finance-summary"><div><Wallet size={18}/><small>Receita mensal contratada</small><strong data-testid="monthly-total">{money(totals.monthly)}</strong></div><div><Handshake size={18}/><small>Contratos ativos</small><strong>{active.length}<em> / 3 espaços</em></strong></div><div><Award size={18}/><small>Total previsto dos contratos</small><strong>{money(totals.committed)}</strong></div></div>
      <div className="subheading"><h3>Parceiros do clube</h3><span>Um patrocinador por espaço</span></div>
      <div className="sponsor-slots">{Object.entries(slots).map(([key,label])=>{const partner=active.find(o=>o.slot===key);return <article className={`sponsor-slot ${partner?'filled':''}`} key={key}><span className="slot-name">{label}</span>{partner?<><strong style={{color:partner.color}}>{partner.name}</strong><span>{money(partner.monthly)}/mês · {partner.months} meses</span><button disabled={!canManage} onClick={()=>setPending({type:'end',item:partner})}>Encerrar contrato</button></>:<><div className="vacant-slot"><Plus size={21}/></div><span>Espaço disponível</span><small>Escolha uma proposta abaixo</small></>}</article>;})}</div>
      <div className="subheading offers-heading"><h3>Propostas disponíveis <span>{offers.filter(o=>!active.some(a=>a.slot===o.slot)).length}</span></h3><span>Marcas e valores fictícios</span></div>
      <div className="offers-grid">{offers.map(o=>{const signed=state.contracts.includes(o.id);const occupied=active.some(a=>a.slot===o.slot);return <article className={`offer-card ${occupied?'unavailable':''}`} key={o.id}><div className="offer-top"><span className="sponsor-wordmark" style={{color:o.color}}>{o.name}</span><span>{slots[o.slot]}</span></div><p>{o.sector} · {o.tagline}</p><div className="offer-price">{money(o.monthly)}<span>/mês</span></div><dl><div><dt>Duração</dt><dd>{o.months} meses</dd></div><div><dt>Bônus de assinatura</dt><dd>{money(o.bonus)}</dd></div><div><dt>Total do contrato</dt><dd>{money(o.monthly*o.months+o.bonus)}</dd></div></dl><button className="proposal-button" disabled={occupied||!canManage} onClick={()=>setPending({type:'sign',item:o})}>{signed?'Contrato ativo':occupied?'Espaço já ocupado':'Analisar proposta'}{signed?<Check size={15}/>:<ArrowRight size={15}/>}</button></article>;})}</div>
      <div className="module-footnote"><FlaskConical size={15}/><p>Simulação local: marcas, propostas e valores são fictícios e iguais para todos os clubes nesta etapa. Os totais são projeções, não saldo em caixa. Sem passagem do tempo, pagamentos ou vencimentos automáticos. Encerramento sem multa neste teste.</p></div>
    </>}
    {pending&&<Modal title={pending.type==='sign'?'Analisar proposta':pending.type==='end'?'Encerrar contrato':'Conquista de teste'} onClose={()=>setPending(null)}><span className="modal-icon">{tab==='trophies'?<Trophy/>:<Handshake/>}</span><div className="eyebrow">{club.name} · SIMULAÇÃO</div><h2>{pending.type==='sign'?`Uma parceria com ${pending.item.name}.`:pending.type==='end'?`Encerrar com ${pending.item.name}?`:pending.type==='award'?'Uma taça para testar a galeria.':'Remover esta conquista de teste?'}</h2>{pending.type==='sign'?<><p>{slots[pending.item.slot]}. Este espaço ficará ocupado até você encerrar o contrato de teste.</p><dl className="proposal-details"><div><dt>Receita por mês</dt><dd>{money(pending.item.monthly)}</dd></div><div><dt>Duração</dt><dd>{pending.item.months} meses</dd></div><div><dt>Bônus de assinatura</dt><dd>{money(pending.item.bonus)}</dd></div><div><dt>Total previsto</dt><dd>{money(pending.item.monthly*pending.item.months+pending.item.bonus)}</dd></div></dl><p>Valores fictícios. Nenhum pagamento será realizado.</p></>:pending.type==='end'?<p>O espaço será liberado e este contrato sairá das projeções. Não há multa nem movimentação de caixa nesta fase de testes.</p>:<p>{pending.item.name} · 2026. {pending.type==='award'?'Esta conquista será marcada como simulada; ela não representa um título real nem uma competição disputada.':'Somente o registro simulado desta taça será removido.'}</p>}<div className="modal-actions"><button className="secondary" onClick={()=>setPending(null)}>Cancelar</button><button className="primary" onClick={apply}>{pending.type==='sign'?'Assinar contrato':pending.type==='end'?'Confirmar encerramento':pending.type==='award'?'Adicionar conquista de teste':'Remover conquista'}</button></div></Modal>}
  </div>;
}
