import React,{useEffect,useMemo,useRef,useState}from'react';
import { ArrowLeft, ArrowRight, Briefcase, ChevronRight, Download, Dumbbell, FileUp, Footprints, HeartPulse, Play, RotateCcw, Shield, Star, Target, Trophy, UserRound, Users } from 'lucide-react';
import { PLAYER_ARCHETYPES, PLAYER_CAREER_KEY, PLAYER_MATCH_APPROACHES, PLAYER_POSITIONS, PLAYER_TRAINING, TRIAL_DRILLS, answerTrialDrill, completeTrial, createPlayerCareer, parsePlayerCareer, playerCareerOverall, respondPlayerOffer, sanitizePlayerCareer, serializePlayerCareer, setPlayerMatchApproach, setPlayerTraining, simulatePlayerWeek, trialScore } from './player-career-engine.js';
import'./player-career.css';

const positionLabel=id=>PLAYER_POSITIONS.find(x=>x.id===id)?.label||id;
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
function initials(name){return String(name||'LF').split(' ').filter(Boolean).map((x,i,a)=>i===0||i===a.length-1?x[0]:'').join('').slice(0,2).toUpperCase();}
function Face({face={},name='',large=false}){
  return <div className={'pc-face '+(large?'large ':'')+'skin-'+(face.skin??0)+' hair-'+(face.hair??0)+' haircolor-'+(face.hairColor??0)+' shape-'+(face.shape??0)} aria-label={'Retrato criado de '+name}><i className="pc-hair"/><span className="pc-ear left"/><span className="pc-ear right"/><span className="pc-eye left"/><span className="pc-eye right"/><span className="pc-brow left"/><span className="pc-brow right"/><span className="pc-nose"/><span className="pc-mouth"/><b>{initials(name)}</b></div>;
}
function clubById(clubs,id){return clubs.find(c=>String(c.id)===String(id))||null;}
function Creator({clubs,onCreate}){
  const [form,setForm]=useState({name:'',position:'MEI',foot:'right',archetype:'technical',dreamClubId:clubs[0]?.id||'',face:{skin:1,hair:1,hairColor:0,eyes:0,shape:0}});
  const update=(key,value)=>setForm(x=>({...x,[key]:value})),face=(key,value)=>setForm(x=>({...x,face:{...x.face,[key]:Number(value)}}));
  return <section className="pc-creator">
    <div className="pc-creator-intro"><span className="pc-eyebrow">MODO CARREIRA JOGADOR</span><h1>Todo mundo começa com 16.</h1><p>Você cria a identidade. O clube precisa ser conquistado na peneira.</p></div>
    <div className="pc-creator-layout">
      <aside className="pc-face-editor"><Face face={form.face} name={form.name||'Você'} large/><strong>{form.name||'Seu jogador'}</strong><small>16 anos · {positionLabel(form.position)}</small><div className="pc-face-controls"><label>Pele<select value={form.face.skin} onChange={e=>face('skin',e.target.value)}>{[0,1,2,3,4].map(x=><option value={x} key={x}>Tom {x+1}</option>)}</select></label><label>Cabelo<select value={form.face.hair} onChange={e=>face('hair',e.target.value)}>{[0,1,2,3,4,5].map(x=><option value={x} key={x}>Estilo {x+1}</option>)}</select></label><label>Cor<select value={form.face.hairColor} onChange={e=>face('hairColor',e.target.value)}>{[0,1,2,3,4].map(x=><option value={x} key={x}>Cor {x+1}</option>)}</select></label><label>Rosto<select value={form.face.shape} onChange={e=>face('shape',e.target.value)}>{[0,1,2,3].map(x=><option value={x} key={x}>Formato {x+1}</option>)}</select></label></div></aside>
      <div className="pc-form">
        <label className="pc-name-field"><span>Nome do jogador</span><input autoFocus maxLength="40" value={form.name} onChange={e=>update('name',e.target.value)} placeholder="Digite o nome"/></label>
        <div><span className="pc-field-label">Posição</span><div className="pc-choice-grid four">{PLAYER_POSITIONS.map(item=><button key={item.id} className={form.position===item.id?'selected':''} onClick={()=>update('position',item.id)}><strong>{item.label}</strong><small>{item.id}</small></button>)}</div></div>
        <div><span className="pc-field-label">Seu estilo</span><div className="pc-choice-grid">{PLAYER_ARCHETYPES.map(item=><button key={item.id} className={form.archetype===item.id?'selected':''} onClick={()=>update('archetype',item.id)}><strong>{item.label}</strong><small>{item.description}</small></button>)}</div></div>
        <div className="pc-inline-fields"><label><span>Pé dominante</span><select value={form.foot} onChange={e=>update('foot',e.target.value)}><option value="right">Direito</option><option value="left">Esquerdo</option></select></label><label><span>Clube dos sonhos</span><select value={form.dreamClubId} onChange={e=>update('dreamClubId',e.target.value)}>{clubs.slice().sort((a,b)=>a.name.localeCompare(b.name,'pt-BR')).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><small>É uma meta, não uma escolha de clube.</small></label></div>
        <div className="pc-rule-note"><Shield size={17}/><span><strong>Sem atalho para clube.</strong><small>A nota da peneira determina onde você começa. Uma grande atuação pode abrir a base do clube dos sonhos.</small></span></div>
        <button className="pc-primary" disabled={!form.name.trim()} onClick={()=>onCreate(createPlayerCareer(form))}>Ir para a peneira <ArrowRight size={17}/></button>
      </div>
    </div>
  </section>;
}
function Trial({career,clubs,onChange}){
  const answers=career.trial?.answers||{},answered=Object.keys(answers).length,next=TRIAL_DRILLS.find(d=>!answers[d.id]),score=trialScore(career);
  if(!next){
    const dream=clubById(clubs,career.dreamClubId);
    return <section className="pc-trial pc-trial-finish"><Target size={35}/><span className="pc-eyebrow">PENEIRA CONCLUÍDA</span><h2>A comissão está fechando o relatório.</h2><p>Foram cinco testes. A nota será comparada ao nível de exigência das categorias de base.</p><div className="pc-trial-meter"><i style={{width:(score||0)+'%'}}/><b>{score}/100</b></div><small>Sonho declarado: {dream?.name||'—'}</small><button className="pc-primary" onClick={()=>onChange(completeTrial(career,clubs))}>Ver onde fui aprovado <ArrowRight size={17}/></button></section>;
  }
  return <section className="pc-trial"><header><span className="pc-eyebrow">PENEIRA · TESTE {answered+1}/{TRIAL_DRILLS.length}</span><h2>{next.title}</h2><p>{next.copy}</p></header><div className="pc-trial-progress">{TRIAL_DRILLS.map((d,i)=><i key={d.id} className={answers[d.id]?'done':i===answered?'current':''}/>)}</div><div className="pc-trial-choices">{next.choices.map(choice=><button key={choice.id} onClick={()=>onChange(answerTrialDrill(career,next.id,choice.id))}><span>{choice.label}</span><ChevronRight size={17}/></button>)}</div><div className="pc-trial-tip"><Star size={15}/> Não existe resposta perfeita: ousadia aumenta teto de pontuação e também a variância.</div></section>;
}
function StatusCard({career,club}){
  const p=career.player,avg=career.seasonStats.matches?career.seasonStats.totalRating/career.seasonStats.matches:0;
  return <section className="pc-status-card"><div className="pc-player-head"><Face face={p.face} name={p.name}/><div><small>{career.stage==='academy'?'CATEGORIAS DE BASE':career.stage==='retired'?'CARREIRA ENCERRADA':'ELENCO PROFISSIONAL'}</small><h2>{p.name}</h2><span>16{career.age!==16?' → '+career.age:''} anos · {positionLabel(p.position)} · {club?.name||'Sem clube'}</span></div><strong className="pc-ovr">{playerCareerOverall(career)}<small>OVR</small></strong></div><div className="pc-status-metrics"><span><small>Condição</small><b>{Math.round(p.condition)}%</b></span><span><small>Moral</small><b>{Math.round(p.morale)}%</b></span><span><small>Confiança técnico</small><b>{Math.round(p.coachTrust)}%</b></span><span><small>Forma</small><b>{p.form>=0?'+':''}{Number(p.form).toFixed(1)}</b></span><span><small>Média</small><b>{avg?avg.toFixed(1):'—'}</b></span></div>{p.injury&&<div className="pc-injury"><HeartPulse size={16}/><span><strong>{p.injury.label}</strong><small>{p.injury.matchesRemaining} semana(s) estimadas de recuperação</small></span></div>}</section>;
}
function TrialResult({career,club}){
  const report=career.trial?.report;if(!report)return null;
  return <section className={'pc-story-card '+(report.dreamSuccess?'dream-success':'')}><Target size={20}/><div><small>{report.dreamSuccess?'CLUBE DOS SONHOS':'PRIMEIRO CLUBE'}</small><strong>{club?.name||report.clubName}</strong><p>{report.reason}</p></div><b>{career.trial.score}/100</b></section>;
}
function LastMatch({career}){
  const last=career.lastMatch;if(!last)return <section className="pc-panel"><h3>Último compromisso</h3><p className="pc-empty">Sua primeira semana ainda não foi simulada.</p></section>;
  if(last.injured)return <section className="pc-panel"><h3>Última semana</h3><div className="pc-match-result muted"><strong>Em recuperação</strong><span>Você não esteve disponível para a partida.</span></div></section>;
  if(!last.selected)return <section className="pc-panel"><h3>Última semana</h3><div className="pc-match-result muted"><strong>Fora da relação</strong><span>Chance calculada de ser relacionado: {Math.round((last.selectionChance||0)*100)}%.</span></div></section>;
  const p=last.performance;return <section className="pc-panel"><div className="pc-panel-head"><h3>Última partida</h3><span>{last.started?'Titular':'Entrou do banco'}</span></div><div className="pc-match-rating"><strong>{p.rating.toFixed(1)}</strong><span>{p.minutes}'</span><span>{p.goals} gol(s)</span><span>{p.assists} assistência(s)</span>{p.cleanSheet&&<span>sem sofrer gol</span>}</div><small>Chance de ser titular/relacionado nasce de OVR efetivo, forma, condição, moral, confiança do técnico e concorrência.</small></section>;
}
function Dashboard({career,clubs,onChange,onReset}){
  const club=clubById(clubs,career.clubId),p=career.player,focus=PLAYER_TRAINING.find(x=>x.id===career.trainingFocus)||PLAYER_TRAINING[0],approach=PLAYER_MATCH_APPROACHES.find(x=>x.id===career.matchApproach)||PLAYER_MATCH_APPROACHES[1],avg=career.careerStats.matches?career.careerStats.totalRating/career.careerStats.matches:0,retired=career.stage==='retired',contract=career.contract;
  return <div className="pc-dashboard">
    <StatusCard career={career} club={club}/><TrialResult career={career} club={club}/>
    {career.pendingOffer&&<section className={'pc-offer '+(career.pendingOffer.dreamClub?'dream-offer':'')}><Briefcase size={21}/><div><small>{career.pendingOffer.dreamClub?'CLUBE DOS SONHOS · PROPOSTA':'PROPOSTA DE CARREIRA'}</small><strong>{career.pendingOffer.clubName}</strong><p>{career.pendingOffer.role} · {career.pendingOffer.years} anos · {money.format(career.pendingOffer.salaryMonthly||0)}/mês. A oferta vence na semana {career.pendingOffer.expiresWeek}.</p></div><div><button onClick={()=>onChange(respondPlayerOffer(career,clubs,false))}>Ficar</button><button className="accept" onClick={()=>onChange(respondPlayerOffer(career,clubs,true))}>Aceitar</button></div></section>}
    <div className="pc-dashboard-grid">
      <section className="pc-panel player-week-plan"><div className="pc-panel-head"><h3>{retired?'Carreira concluída':'Plano da semana'}</h3><Dumbbell size={17}/></div>{retired?<><p>A trajetória terminou, mas estatísticas, prêmios e linha do tempo permanecem neste save.</p><div className="pc-retired-summary"><Trophy size={19}/><span><strong>{career.careerStats.matches} jogos · {career.careerStats.goals} gols</strong><small>{career.awards?.length||0} prêmio(s) · {career.age} anos no encerramento</small></span></div></>:<><p>Treino define evolução e desgaste; postura em campo muda protagonismo, confiança do técnico e risco físico.</p><small className="pc-subheading">TREINO</small><div className="pc-training-list">{PLAYER_TRAINING.map(item=><button key={item.id} className={career.trainingFocus===item.id?'active':''} onClick={()=>onChange(setPlayerTraining(career,item.id))}><strong>{item.label}</strong><small>{item.description}</small></button>)}</div><small className="pc-subheading">POSTURA EM JOGO</small><div className="pc-approach-list">{PLAYER_MATCH_APPROACHES.map(item=><button key={item.id} className={career.matchApproach===item.id?'active':''} onClick={()=>onChange(setPlayerMatchApproach(career,item.id))}><strong>{item.label}</strong><small>{item.description}</small></button>)}</div><div className="pc-current-focus">Treino: <b>{focus.label}</b> · Postura: <b>{approach.label}</b></div><button className="pc-primary" onClick={()=>onChange(simulatePlayerWeek(career,clubs))}><Play size={16}/> Avançar semana {career.week+1}</button></>}</section>
      <LastMatch career={career}/>
      <section className="pc-panel"><div className="pc-panel-head"><h3>Temporada {career.season}</h3><Trophy size={17}/></div><div className="pc-stat-grid"><span><b>{career.seasonStats.matches}</b><small>Jogos</small></span><span><b>{career.seasonStats.starts}</b><small>Titular</small></span><span><b>{career.seasonStats.goals}</b><small>Gols</small></span><span><b>{career.seasonStats.assists}</b><small>Assist.</small></span><span><b>{career.seasonStats.minutes}</b><small>Minutos</small></span><span><b>{avg?avg.toFixed(1):'—'}</b><small>Média carreira</small></span></div></section>
      <section className="pc-panel"><div className="pc-panel-head"><h3>Atributos</h3><Footprints size={17}/></div><div className="pc-attributes">{Object.entries(p.attributes).filter(([key])=>key!=='goalkeeping'||p.position==='GOL').map(([key,value])=><span key={key}><small>{{finishing:'Finalização',passing:'Passe',defending:'Defesa',pace:'Velocidade',physical:'Físico',technique:'Técnica',goalkeeping:'Goleiro'}[key]||key}</small><b>{Math.round(value)}</b><i><em style={{width:clampUi(value)+'%'}}/></i></span>)}</div></section>
      <section className="pc-panel pc-contract-panel"><div className="pc-panel-head"><h3>Contrato & carreira</h3><Briefcase size={17}/></div>{contract?<dl><div><dt>Clube</dt><dd>{contract.clubName}</dd></div><div><dt>Salário</dt><dd>{money.format(contract.salaryMonthly)}/mês</dd></div><div><dt>Vínculo</dt><dd>até {contract.expirySeason}</dd></div><div><dt>Papel</dt><dd>{contract.role}</dd></div></dl>:<p className="pc-empty">O primeiro vínculo aparece depois da aprovação na peneira.</p>}<div className="pc-career-flags"><span><small>Reputação</small><b>{Math.round(p.reputation||0)}/100</b></span><span><small>Seleção</small><b>{career.nationalTeamStatus==='called-up'?'Convocado':'Ainda não'}</b></span><span><small>Prêmios</small><b>{career.awards?.length||0}</b></span></div></section>
      <section className="pc-panel pc-news-panel"><div className="pc-panel-head"><h3>Notícias da carreira</h3><Star size={17}/></div>{career.news?.length?<div>{career.news.slice(0,5).map(item=><article key={item.id}><small>{item.season} · S{item.week??0}</small><strong>{item.title}</strong><p>{item.text}</p></article>)}</div>:<p className="pc-empty">As primeiras notícias surgem conforme a carreira avança.</p>}</section>
    </div>
    <section className="pc-timeline"><div className="pc-panel-head"><h3>Linha do tempo</h3><UserRound size={17}/></div>{career.timeline.slice(0,12).map(item=><article key={item.id}><b>{item.season}<small>S{item.week??0}</small></b><div><strong>{item.title}</strong><p>{item.text}</p></div></article>)}</section>
    <button className="pc-reset" onClick={onReset}><RotateCcw size={14}/> Criar outra carreira de jogador</button>
  </div>;
}
const clampUi=value=>Math.max(0,Math.min(100,Number(value)||0));
export default function PlayerCareer({clubs,onExit}){
  const fileInput=useRef(null),[career,setCareer]=useState(()=>{try{return sanitizePlayerCareer(JSON.parse(localStorage.getItem(PLAYER_CAREER_KEY)||'null'),clubs);}catch{return null;}}),[notice,setNotice]=useState('');
  useEffect(()=>{try{if(career)localStorage.setItem(PLAYER_CAREER_KEY,JSON.stringify(career));else localStorage.removeItem(PLAYER_CAREER_KEY);}catch{setNotice('O navegador bloqueou o autosave. Exporte um backup se continuar jogando.');}},[career]);
  const club=useMemo(()=>clubById(clubs,career?.clubId),[clubs,career?.clubId]);
  function download(){if(!career)return;const blob=new Blob([serializePlayerCareer(career)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='linha-de-frente-jogador-'+career.player.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/gi,'-').toLowerCase()+'.ldfp';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500);}
  async function load(file){if(!file)return;try{setCareer(parsePlayerCareer(await file.text(),clubs));setNotice('Carreira de jogador carregada.');}catch(e){setNotice(e.message||'Arquivo inválido.');}if(fileInput.current)fileInput.current.value='';}
  function reset(){if(confirm('Criar uma nova carreira de jogador? O autosave atual será substituído.'))setCareer(null);}
  return <main className="player-career-shell"><header className="pc-topbar"><button onClick={onExit}><ArrowLeft size={16}/> Menu</button><div><span className="pc-brand">L<span>F</span></span><strong>CARREIRA JOGADOR</strong></div><div className="pc-save-actions">{career&&<button onClick={download}><Download size={15}/> Backup</button>}<button onClick={()=>fileInput.current?.click()}><FileUp size={15}/> Importar</button><input ref={fileInput} hidden type="file" accept=".ldfp,application/json" onChange={e=>load(e.target.files?.[0])}/></div></header>{notice&&<div className="pc-notice">{notice}</div>}<div className="pc-body">{!career?<Creator clubs={clubs} onCreate={setCareer}/>:career.stage==='trial'?<Trial career={career} clubs={clubs} onChange={setCareer}/>:<Dashboard career={career} clubs={clubs} onChange={setCareer} onReset={reset}/>}</div><footer className="pc-footer"><span>LINHA DE FRENTE · RC4</span><span>{club?club.name:'A jornada começa na peneira'}</span></footer></main>;
}
